name: Auto Deploy Bot Lokal

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Ganti dari 'ubuntu-latest' ke 'self-hosted'
    runs-on: self-hosted 

    steps:
      # Langkah 1: GitHub akan mengirim kode terbaru ke folder Runner
      - name: Checkout Code
        uses: actions/checkout@v4

      # Langkah 2: Jalankan perintah langsung di server lokal
      - name: Install & Restart
        run: |
          # Masuk ke folder proyek yang dikelola admin
          cd /home/admin/tesbotwa
          
          # Ambil update terbaru dari GitHub
          git pull origin main
          
          # Install library baru jika ada
          npm install --production
          
          # Restart proses PM2 spesifik kamu
          sudo pm2 restart botwapanelweb || sudo pm2 start index.js --name botwapanelweb
